# Generated by Django 2.1.4 on 2018-12-12 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('NombreLista', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('Estado', models.CharField(choices=[('F', 'Finalizada'), ('I', 'Incompleta')], default='I', max_length=1)),
                ('valorPresupuestado', models.IntegerField()),
                ('costoReal', models.IntegerField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=255)),
                ('ValorProducto', models.IntegerField()),
                ('Notas', models.TextField()),
                ('Estado', models.CharField(choices=[('C', 'Comprado'), ('N', 'No Comprado')], default='N', max_length=1)),
                ('Lista', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='listasApp.Lista')),
            ],
        ),
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=255)),
                ('NombreSucursal', models.CharField(max_length=255)),
                ('Direccion', models.TextField()),
                ('Ciudad', models.CharField(max_length=255)),
                ('Region', models.CharField(max_length=255)),
                ('Estado', models.CharField(choices=[('P', 'Pendiente'), ('A', 'Aprobada')], default='P', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='Tienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='listasApp.Tienda'),
        ),
    ]
